language: python
env:
  global:
    - IMAGE_NAME=namelivia/plants-server
services:
    - docker
before_install:
  - docker build . --tag "$IMAGE_NAME"
script: bash ./run_tests
before_deploy:
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_TAG}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${TRAVIS_TAG}"
  on:
    tags: true
    branch: master
after_sucess:
    - bash <(curl -s https://codecov.io/bash)
