version: '3'
services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: plants-server-app
    restart: unless-stopped
    depends_on:
        - database
    tty: true
    working_dir: /app
    expose:
      - "80"
    volumes:
      - ./:/app
    environment:
      DATABASE_URL: "postgresql://user:password@database/plants"
      TEST_DATABASE_URL: "sqlite:///./test.db"
      NOTIFICATIONS_SERVICE_ENDPOINT: "http://notifications-service:80"
      IMAGES_SERVICE_ENDPOINT: "http://images-service:80/image"
    command: [
        "pipenv",
        "run",
        "uvicorn",
        "app.main:app",
        "--reload",
        "--host=0.0.0.0",
        "--port=80"
    ]
    networks:
      - app-network

  #This could be done with just one container, just adding two for simplicity
  #Postgres Service
  database:
    image: postgres:latest
    container_name: plants-server-database
    restart: unless-stopped
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: plants
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - app-network

  database2:
    image: postgres:latest
    container_name: airflow-database
    restart: unless-stopped
    tty: true
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    networks:
      - app-network

  #Pomerium proxy
  plants-auth-proxy:
    image: pomerium/pomerium:v0.11.0-rc1
    container_name: plants_proxy
    restart: unless-stopped
    tty: true
    ports:
      - "443:443"
    volumes:
      - ./pomerium/config.yaml:/pomerium/config.yaml
      - ./certs/localhost.crt:/pomerium/cert.pem:ro
      - ./certs/localhost.key:/pomerium/privkey.pem:ro
    networks:
      - app-network

  #Images service
  images-service:
    image: minimalcompact/thumbor:latest
    container_name: images-service
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
        UPLOAD_ENABLED: "True"
        LOG_LEVEL: "debug"
        ALOW_UNSAFE_URL: "True"

  #Scheduler service
  scheduler-service:
    image: apache/airflow:latest
    command: scheduler
    depends_on:
        - database
    container_name: scheduler-service
    restart: unless-stopped
    tty: true
    networks:
      - app-network
    environment:
        AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@database2:5433/airflow"
        AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
    volumes:
        - ./dags:/opt/airflow/dags


#Docker Networks
networks:
  app-network:
    driver: bridge
