"""Add journaling key to plants

Revision ID: 56a2f2c760af
Revises: dc7bec5b2128
Create Date: 2021-01-04 17:20:15.447010

"""
from alembic import op
import sqlalchemy as sa
from fastapi_utils.guid_type import GUID


# revision identifiers, used by Alembic.
revision = "56a2f2c760af"
down_revision = "dc7bec5b2128"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.add_column(sa.Column("journaling_key", GUID(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.drop_column("journaling_key")

    # ### end Alembic commands ###
