"""Add watering timestamp

Revision ID: 7fcff736c054
Revises: 56a2f2c760af
Create Date: 2021-01-05 16:06:16.840404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fcff736c054'
down_revision = '56a2f2c760af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_watering', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('last_watering')

    # ### end Alembic commands ###
