"""rename_column

Revision ID: 8bfcf28920ea
Revises: b77079c9f6a3
Create Date: 2022-02-19 19:20:06.925270

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8bfcf28920ea"
down_revision = "b77079c9f6a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.alter_column(
            "days_until_watering", nullable=False, new_column_name="water_every"
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.alter_column(
            "water_every", nullable=False, new_column_name="days_until_watering"
        )
    # ### end Alembic commands ###
