"""Add alive boolean

Revision ID: b77079c9f6a3
Revises: a4aa0f43b257
Create Date: 2021-04-01 10:32:07.183286

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b77079c9f6a3"
down_revision = "a4aa0f43b257"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("alive", sa.Boolean(), server_default="TRUE", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("plants", schema=None) as batch_op:
        batch_op.drop_column("alive")

    # ### end Alembic commands ###
