"""Add image field to plants

Revision ID: f381be3fce18
Revises: 7f5dd2af6e23
Create Date: 2020-12-24 12:44:17.676039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f381be3fce18'
down_revision = '7f5dd2af6e23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'image')
    # ### end Alembic commands ###
