name: Build
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up development Docker Buildx
        id: development_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Build testing container
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.development_builder.outputs.name }}
          target: development
          load: true
          tags: plants-server-testing:latest
      - 
        name: Run tests
        uses: addnab/docker-run-action@v1
        with:
          image: plants-server-testing:latest
          run: TESTING=True TEST_DATABASE_URL=sqlite:///./test.db IMAGES_SERVICE_ENDPOINT=http://images-service:80/image pipenv run pytest
      - 
        name: Send test coverage to codecov
        uses: addnab/docker-run-action@v1
        with:
          image: plants-server-testing:latest
          run: pipenv run codecov --commit=${{ github.sha }}
      -
        name: Set up production Docker Buildx
        id: production_builder
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push production container
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          builder: ${{ steps.production_builder.outputs.name }}
          target: production
          tags: namelivia/plants-server:latest
