# Docker build and test
name: Docker build and test
on:
  push:
    branches:
      - master
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          target: development
          tags: namelivia/plants-server:latest
      - 
        name: Execute command
        uses: addnab/docker-run-action@v1
        with:
          image: namelivia/plants-server:latest
          run: echo "hello world"
